'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Billing
    
    '''<summary>
    '''CompanyNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''StartDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EndDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''StartDateTextBoxCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTextBoxCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''EndDateTextBoxCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDateTextBoxCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''OrdersGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrdersGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ShippingOrdersSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingOrdersSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ExportToQuickBooksButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportToQuickBooksButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''InvoiceBatchDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvoiceBatchDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''InvoiceBatchHistorySqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvoiceBatchHistorySqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ExportBatchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportBatchButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ExportSunbeltBatchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportSunbeltBatchButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''InvoiceBatchGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvoiceBatchGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''InvoiceBatchReportSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InvoiceBatchReportSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
