'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompanyPopupWrapperWebUserControl

    '''<summary>
    '''CompanyModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''CompanyPopupPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyPopupPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CompanyPopupEditorWebUserControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyPopupEditorWebUserControl1 As Global.CL_TicketingApp.CompanyPopupEditorWebUserControl

    '''<summary>
    '''MessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CompanyPopupLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyPopupLink As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
