'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InvoicePrep
    
    '''<summary>
    '''CustomerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''StartDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EndDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ExportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CompanySqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanySqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''StartDateTextBoxCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDateTextBoxCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''EndDateTextBoxCalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDateTextBoxCalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''BatchOfPORsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BatchOfPORsButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BatchOfInvoicesButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BatchOfInvoicesButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''QueueRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QueueRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''QueueSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QueueSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
