'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewOrderComplete
    
    '''<summary>
    '''PrintButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PrintBOLButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PrintBOLButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CopiesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CopiesTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CopyButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CopyButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CopyMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CopyMessageLabel As Global.System.Web.UI.WebControls.Label
End Class
