'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewOrder
    
    '''<summary>
    '''ShippingOrderIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingOrderIDHiddenField As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''OrderStatusDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderStatusDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''OrderStatusSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderStatusSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''ShippingOrderNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShippingOrderNumberTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OrderDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderDateTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerSelectorUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerSelectorUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''CustomerDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CustomerContactTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerContactTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomerBillAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerBillAmount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ExtraCharge1AmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraCharge1AmountTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ExtraCharge1DescriptionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraCharge1DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''updateProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateProgress As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''CarrierSelectorUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierSelectorUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''CarrierIDHiddenField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierIDHiddenField As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''CarrierTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NewCarrierPopUpControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewCarrierPopUpControl As Global.CL_TicketingApp.CompanyPopupWrapperWebUserControl
    
    '''<summary>
    '''CarrierNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CarrierAutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierAutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''CompanySqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanySqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''CarrierPayAmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPayAmountTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CarrierContactTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierContactTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ExtraPay1AmountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraPay1AmountTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CarrierPhoneTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierPhoneTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ExtraPay1DescriptionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExtraPay1DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CarrierFaxTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierFaxTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CitationContactTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CitationContactTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EmailTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LoadTypeDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadTypeDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LoadTypeSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadTypeSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''DriverNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DriverNameTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TarpDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TarpDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CellPhoneTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CellPhoneTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''WeightTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeightTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AddActivityWebUserControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddActivityWebUserControl1 As Global.CL_TicketingApp.AddActivityWebUserControl
    
    '''<summary>
    '''AddActivityWebUserControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddActivityWebUserControl2 As Global.CL_TicketingApp.AddActivityWebUserControl
    
    '''<summary>
    '''AddActivityWebUserControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddActivityWebUserControl3 As Global.CL_TicketingApp.AddActivityWebUserControl
    
    '''<summary>
    '''AddActivityWebUserControl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddActivityWebUserControl4 As Global.CL_TicketingApp.AddActivityWebUserControl
    
    '''<summary>
    '''NotesTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotesTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OrdersSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrdersSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button
End Class
